version: '3'

services:
  db:
    image: postgres:10.1-alpine
  redis:
    image: redis:alpine
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: cms
    volumes:
      - .:/cms
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A CrysisAlert worker -l info
    volumes:
      - .:/cms
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A CrysisAlert beat -l info
    volumes:
      - .:/cms
    depends_on:
      - db
      - redis