# Generated by Django 2.1.1 on 2018-10-28 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisisreport',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crisisreport',
            name='crisis_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crisis', to='app.Crisis'),
        ),
    ]
