# Generated by Django 2.1.1 on 2018-10-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='contact_num',
            field=models.CharField(max_length=8),
        ),
    ]
