# Generated by Django 2.1.1 on 2018-10-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181028_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistance',
            name='crisis',
        ),
        migrations.AddField(
            model_name='crisisreport',
            name='assistance',
            field=models.ManyToManyField(related_name='assistance', to='app.Assistance'),
        ),
    ]
