# Generated by Django 2.1.1 on 2018-10-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181019_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='type_of_assistance',
            field=models.CharField(choices=[('E', 'Emergency Ambulance'), ('R', 'Rescue and Evacuation'), ('F', 'Fire-Fighting'), ('G', 'Gas Leak Control')], max_length=1),
        ),
    ]
