# Generated by Django 2.1.1 on 2018-11-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181019_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='contact_num',
            field=models.CharField(max_length=11),
        ),
    ]
